baseURL: "https://loudrxiv.github.io"
title: A loudrxiv - A website for the academically-stunted
theme: WonderMod
copyright: '[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)'
enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true # added from forked repo in order to add emojis... (https://www.webfx.com/tools/emoji-cheat-sheet/)

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: Mark Maher Makram Ebeid Attalla
  # author: ["Me", "You"] # multiple authors
  description: A website for the academically-stunted
  keywords: [Privacy, Ph.D., Animation, Political Theory, Film, Mental Health, Writing, History, Comedy, Public Speaking & Outreach, Music, Reading, Security]
  defaultTheme: dark # dark, light
  disableThemeToggle: false
  images: ["/waving_snail.png"]
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowWordCount: true
  ShowToc: true
  ShowRssButtonInSectionTermList: true
  ShowFullTextinRSS: true
  ShowCodeCopyButtons: true

  assets:
    disableHLJS: true
    disableFingerprinting: false
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"
    snail: "snail.gif"

  label:
    text: "loudRxiv"
    icon: "/snail.gif"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: A loud archive...
    subtitle: "My front-facing online notebook; I can share this with others..."
    buttons:
      - name: About
        url: about
      - name: Interests
        url: interests
      - name: Research
        url: research
      - name: bioZone
        url: "https://www.youtube.com/@bioZone101/about"

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/markus-ebeid/"
    - name: github
      url: "https://github.com/loudrxiv"
    - name: letterboxd
      url: local_letterboxd
    - name: goodreads
      url: local_goodreads
    - name: email
      url: "mailto:mebeid1@umbc.edu"
    - name: rss
      url: /index.xml

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/PrivSec-dev/privsec.dev/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary"]

#Enabling Search
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

# Enable Chroma
markup:
    highlight:
        style: dracula
        lineNos: false
        noClasses: false
        guessSyntax: true

menu:
  main:
    - identifier: Categories
      name: Categories
      url: /posts/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: Search
      name: Search
      url: /search/
      weight: 30
    - identifier: Resources
      name: Resources
      url: /resources
      weight: 40

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: false
    enableDNT: true
    simple: false
  vimeo:
    disable: false
    enableDNT: true
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true
